In [29]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [31]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [32]:
X = dataset.iloc[:,3:-1].values

In [33]:
y = dataset.iloc[:,-1].values

In [34]:
# Label Encoded
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
X[:,2] = LE.fit_transform(X[:,2])

In [35]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [36]:
# One hot encoding of Geographic column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [37]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [39]:
X_train.size

96000

In [40]:
#Feature Scaling ----> Absolutely fundamental in Deep Learning
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =  sc.fit_transform(X_train)
X_test  = sc.fit_transform(X_test)

In [41]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [42]:
ann = tf.keras.models.Sequential() # Start of Sequence of Layers 

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu')) # A hidden layer with 6 neurons and activation function as ReLu

# Input layer will be the feature, above one is the layer after the input layer

In [44]:
# Second Hidden Layer
ann.add(tf.keras.layers.Dense(units=6, activation= 'relu'))

In [45]:
# Output Layer 
ann.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

In [46]:
# Compiling the ANN

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'] ) # Optimizer perform the stochastic Gradient Descent
#binary_crossentropy because I am doing binary classification, we'd have used categorical_crossentropy if there were more category and the activation could be 'softmax'
#matrics - on which ground you would evaluate your neural network

In [47]:
#Training the ANN
ann.fit(X_train, y_train, batch_size=32,epochs=100)

W1108 13:17:15.187597 54860 ag_logging.py:146] AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x00000150CAADC840> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Epoch 1/100
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
250/250 [==============================] - 0s 668us/step - loss: 0.6296 - accuracy: 0.6787
Epoch 2/100
250/250 [==============================] - 0s 648us/step - loss: 0.4776 - accuracy: 0.7964
Epoch 3/100
250/250 [==============================] - 0s 644us/step - loss: 0.4431 - accuracy: 0.8026
Epoch 4/100
250/250 [==============================] - 0s 736us/step - loss: 0.4324 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 712us/step - loss: 0.4278 - accuracy: 0.81040s - loss: 0.4306 - accuracy: 
Epoch 6/100
250/250 [==============================] - 0s 680us/step - loss: 0.4248 - accuracy: 0.8124
Epoch 7/100
250/250 [====================

250/250 [==============================] - 0s 600us/step - loss: 0.3384 - accuracy: 0.8608
Epoch 76/100
250/250 [==============================] - 0s 556us/step - loss: 0.3384 - accuracy: 0.8616
Epoch 77/100
250/250 [==============================] - 0s 640us/step - loss: 0.3383 - accuracy: 0.8587
Epoch 78/100
250/250 [==============================] - 0s 612us/step - loss: 0.3380 - accuracy: 0.8596
Epoch 79/100
250/250 [==============================] - 0s 692us/step - loss: 0.3380 - accuracy: 0.8610
Epoch 80/100
250/250 [==============================] - 0s 700us/step - loss: 0.3378 - accuracy: 0.8611
Epoch 81/100
250/250 [==============================] - 0s 620us/step - loss: 0.3379 - accuracy: 0.8616
Epoch 82/100
250/250 [==============================] - 0s 644us/step - loss: 0.3378 - accuracy: 0.8611
Epoch 83/100
250/250 [==============================] - 0s 568us/step - loss: 0.3373 - accuracy: 0.8605
Epoch 84/100
250/250 [==============================] - 0s 576us/step - loss:

In [48]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5) # Any input of the predict method must to an 2d array

W1108 13:17:31.619596 54860 ag_logging.py:146] AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x00000150CCBF68C8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[False]]


In [49]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [50]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1523   72]
 [ 197  208]]


0.8655